In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
import warnings
warnings.filterwarnings('ignore')

In [5]:
df=pd.read_csv(r'D:\TUFEL\Data scientist pro\Data analysis project\Capstone Project\Car Dataset Cleaned.csv')

In [10]:
df.head(1)

,vehicle_uid,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,car_record_id,car_age,price_category,km_category,owner_count,fuel_transmission,brand,price_per_km,is_diesel
0,CAR_000001,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner,1,18,Low,Medium,0,Petrol_Manual,Maruti,0.86,0

In [11]:
data1 = df[['vehicle_uid', 'name', 'year', 'fuel', 'seller_type', 'transmission', 'owner', 'car_age', 'brand' ]]

In [12]:
data2 = df[['vehicle_uid', 'selling_price', 'km_driven', 'price_category', 'km_category' ]]

In [17]:
data1.to_csv('Vehical_info.csv',index=False)

In [16]:
pwd

'C:\\Users\\Admin\\Data Analyst Project'

In [15]:
data2.to_csv('Vehical_sales.csv',index=False)

In [7]:
df.isnull().sum()

vehicle_uid          0
name                 0
year                 0
selling_price        0
km_driven            0
fuel                 0
seller_type          0
transmission         0
owner                0
car_record_id        0
car_age              0
price_category       0
km_category          0
owner_count          0
fuel_transmission    0
brand                0
price_per_km         0
is_diesel            0
dtype: int64

In [8]:
# Should Be Deleted
# 1.Vehicle id
# 2.Car record id
# 3.Owner count
# 4.Fuel Transmission
# 5.is diesel

In [9]:
df.drop(['vehicle_uid','fuel_transmission','is_diesel'],axis=1)

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,car_record_id,car_age,price_category,km_category,owner_count,brand,price_per_km
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner,1,18,Low,Medium,0,Maruti,0.86
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner,2,18,Low,Medium,0,Maruti,2.70
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner,3,13,Low,Medium,0,Hyundai,6.00
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner,4,8,Low,Medium,0,Datsun,5.43
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner,5,11,Low,High,0,Honda,3.19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,60000,Diesel,Individual,Manual,Second Owner,4336,11,Mid,High,0,Hyundai,5.12
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Diesel,Individual,unknown,Second Owner,4337,11,Mid,High,0,Hyundai,5.12
4337,Maruti 800 AC BSIII,2009,110000,83000,Petrol,Individual,Manual,Second Owner,4338,16,Low,High,0,Maruti,1.33
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000,60000,Diesel,Individual,Manual,First Owner,4339,9,High,High,0,Hyundai,9.61
4339,Renault KWID RXT,2016,4461000,40000,Petrol,Individual,Manual,First Owner,4340,9,Low,Medium,0,Renault,5.62