In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
df=pd.read_csv(r'D:\TUFEL\Data scientist pro\Data analysis project\1 Full Projects\Bank Churn\bank_churn_dataset.csv')

In [55]:
df2=pd.read_csv(r'D:\TUFEL\Data scientist pro\Data analysis project\1 Full Projects\Bank Churn\bank_churn_dataset.csv')

In [57]:
df2.isnull().sum()

customer_id                  0
age                          0
gender                     117
state                        0
city                         0
pin_code                     0
marital_status             295
education                    0
occupation                   0
join_date                    0
tenure_years                 0
account_type                 0
account_segment              0
annual_income              202
balance                    303
credit_score               301
num_products                 0
has_credit_card              0
has_loan                     0
has_insurance                0
has_demat                    0
has_mutual_fund              0
loan_amount                  0
loan_emi                     0
credit_limit                 0
credit_utilization_pct       0
monthly_txn_count          200
monthly_debit_amt            0
monthly_credit_amt           0
avg_txn_value                0
online_txn_pct               0
atm_withdrawal_freq          0
upi_txn_count                0
net_banking_logins           0
mobile_app_logins            0
branch_visits                0
complaints_last_year         0
complaint_resolved        5627
nps_score                  323
csat_score                 410
days_since_last_txn          0
days_since_last_login        0
is_dormant                   0
inactive_6m                  0
churn                        0
dtype: int64

In [3]:
df.head()

,customer_id,age,gender,state,city,pin_code,marital_status,education,occupation,join_date,...,branch_visits,complaints_last_year,complaint_resolved,nps_score,csat_score,days_since_last_txn,days_since_last_login,is_dormant,inactive_6m,churn
0,CUST0009824,36,Male,UP,Agartala,77280,Married,Post-Graduate,Homemaker,19-10-2016,...,2,0,NaN,7.0,2.0,26,5,0,0,0
1,CUST0000034,28,Male,West Bengal,Jalgaon,58419,Married,Post-Graduate,Self-Employed,30-10-2014,...,1,0,NaN,9.0,5.0,4,1,0,0,0
2,CUST0001370,30,Male,Maharashtra,Sirsa,618183,Married,Graduate,Business Owner,09-10-2014,...,1,0,NaN,7.0,4.0,23,16,0,0,0
3,CUST0003621,24,Male,Karnataka,Ghaziabad,543229,Married,Graduate,Self-Employed,23-08-2022,...,2,1,1.0,8.0,2.0,1,12,0,0,0
4,CUST0003273,53,Male,Delhi,Latur,723494,Married,High School,Salaried,13-03-2018,...,2,0,NaN,8.0,3.0,3,1,0,0,0

# Phase 1: Data Understanding

## 1. Check the shape of the dataset.

In [4]:
print(df.shape)

(10080, 45)

## 2. Display all column names.

In [5]:
pd.DataFrame(df.columns,columns=['Col_names'])

                 Col_names
0              customer_id
1                      age
2                   gender
3                    state
4                     city
5                 pin_code
6           marital_status
7                education
8               occupation
9                join_date
10            tenure_years
11            account_type
12         account_segment
13           annual_income
14                 balance
15            credit_score
16            num_products
17         has_credit_card
18                has_loan
19           has_insurance
20               has_demat
21         has_mutual_fund
22             loan_amount
23                loan_emi
24            credit_limit
25  credit_utilization_pct
26       monthly_txn_count
27       monthly_debit_amt
28      monthly_credit_amt
29           avg_txn_value
30          online_txn_pct
31     atm_withdrawal_freq
32           upi_txn_count
33      net_banking_logins
34       mobile_app_logins
35           branch_visits
36    complaints_last_year
37      complaint_resolved
38               nps_score
39              csat_score
40     days_since_last_txn
41   days_since_last_login
42              is_dormant
43             inactive_6m
44                   churn

## 3. Check data types of all columns.

In [6]:
df.dtypes

customer_id                object
age                         int64
gender                     object
state                      object
city                       object
pin_code                    int64
marital_status             object
education                  object
occupation                 object
join_date                  object
tenure_years              float64
account_type               object
account_segment            object
annual_income             float64
balance                   float64
credit_score              float64
num_products                int64
has_credit_card             int64
has_loan                    int64
has_insurance               int64
has_demat                   int64
has_mutual_fund             int64
loan_amount               float64
loan_emi                  float64
credit_limit              float64
credit_utilization_pct    float64
monthly_txn_count         float64
monthly_debit_amt         float64
monthly_credit_amt        float64
avg_txn_value             float64
online_txn_pct            float64
atm_withdrawal_freq         int64
upi_txn_count               int64
net_banking_logins          int64
mobile_app_logins           int64
branch_visits               int64
complaints_last_year        int64
complaint_resolved        float64
nps_score                 float64
csat_score                float64
days_since_last_txn         int64
days_since_last_login       int64
is_dormant                  int64
inactive_6m                 int64
churn                       int64
dtype: object

## 4. Identify missing values in each column.

In [7]:
df.isnull().sum()

customer_id                  0
age                          0
gender                     117
state                        0
city                         0
pin_code                     0
marital_status             295
education                    0
occupation                   0
join_date                    0
tenure_years                 0
account_type                 0
account_segment              0
annual_income              202
balance                    303
credit_score               301
num_products                 0
has_credit_card              0
has_loan                     0
has_insurance                0
has_demat                    0
has_mutual_fund              0
loan_amount                  0
loan_emi                     0
credit_limit                 0
credit_utilization_pct       0
monthly_txn_count          200
monthly_debit_amt            0
monthly_credit_amt           0
avg_txn_value                0
online_txn_pct               0
atm_withdrawal_freq          0
upi_txn_count                0
net_banking_logins           0
mobile_app_logins            0
branch_visits                0
complaints_last_year         0
complaint_resolved        5627
nps_score                  323
csat_score                 410
days_since_last_txn          0
days_since_last_login        0
is_dormant                   0
inactive_6m                  0
churn                        0
dtype: int64

## 5. Calculate the percentage of missing values.

In [8]:
round(df.isnull().sum()/len(df)*100,2)

customer_id                0.00
age                        0.00
gender                     1.16
state                      0.00
city                       0.00
pin_code                   0.00
marital_status             2.93
education                  0.00
occupation                 0.00
join_date                  0.00
tenure_years               0.00
account_type               0.00
account_segment            0.00
annual_income              2.00
balance                    3.01
credit_score               2.99
num_products               0.00
has_credit_card            0.00
has_loan                   0.00
has_insurance              0.00
has_demat                  0.00
has_mutual_fund            0.00
loan_amount                0.00
loan_emi                   0.00
credit_limit               0.00
credit_utilization_pct     0.00
monthly_txn_count          1.98
monthly_debit_amt          0.00
monthly_credit_amt         0.00
avg_txn_value              0.00
online_txn_pct             0.00
atm_withdrawal_freq        0.00
upi_txn_count              0.00
net_banking_logins         0.00
mobile_app_logins          0.00
branch_visits              0.00
complaints_last_year       0.00
complaint_resolved        55.82
nps_score                  3.20
csat_score                 4.07
days_since_last_txn        0.00
days_since_last_login      0.00
is_dormant                 0.00
inactive_6m                0.00
churn                      0.00
dtype: float64

## 6. Find duplicate rows.

In [9]:
df[df.duplicated()]

,customer_id,age,gender,state,city,pin_code,marital_status,education,occupation,join_date,...,branch_visits,complaints_last_year,complaint_resolved,nps_score,csat_score,days_since_last_txn,days_since_last_login,is_dormant,inactive_6m,churn
667,CUST0005351,49,Male,UP,Kolkata,891262,Single,Graduate,Salaried,02-10-2021,...,0,4,1.0,8.0,4.0,6,7,0,0,0
696,CUST0009691,48,Other,Tamil Nadu,Shivpuri,973414,Married,Doctorate,Self-Employed,28-03-2017,...,2,0,NaN,9.0,4.0,11,9,0,0,0
1381,CUST0004773,50,Female,West Bengal,Thane,935016,Single,Graduate,Freelancer,27-11-2015,...,4,1,1.0,7.0,4.0,1,11,0,0,0
2816,CUST0004636,18,Male,Delhi,Kurnool,258649,Married,Unknown,Salaried,18-12-2011,...,3,0,NaN,3.0,4.0,10,6,0,0,0
2907,CUST0001444,25,Female,Karnataka,Ludhiana,898799,Married,Graduate,Self-Employed,12-12-2014,...,0,0,NaN,9.0,5.0,27,2,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9819,CUST0002870,57,Female,West Bengal,Jalna,22254,Married,Post-Graduate,Business Owner,27-01-2020,...,0,0,NaN,10.0,4.0,14,11,0,0,0
9831,CUST0001649,57,Male,West Bengal,Darbhanga,924199,Single,High School,Self-Employed,26-10-2019,...,1,0,NaN,5.0,5.0,0,0,0,0,0
9919,CUST0005576,18,Male,Tamil Nadu,Darbhanga,28911,Single,Graduate,Business Owner,12-03-2022,...,2,1,1.0,8.0,4.0,30,4,0,0,0
9931,CUST0007506,18,Male,Tamil Nadu,Sikar,504437,Married,Graduate,Business Owner,16-04-2010,...,0,1,1.0,10.0,5.0,24,10,0,0,0
9935,CUST0005916,30,Female,Telangana,Udaipur,803999,Single,Graduate,Retired,30-07-2022,...,1,1,1.0,10.0,3.0,4,0,0,0,0

In [10]:
df.duplicated().sum()

np.int64(80)

## 7. Check whether Customer_ID contains duplicates.

In [11]:
df['customer_id'].duplicated().sum()

np.int64(80)

## 8. Count unique values in categorical columns.

In [12]:
df.select_dtypes(include='object').nunique()

customer_id        10000
gender                 3
state                 10
city                 316
marital_status         4
education              5
occupation             7
join_date           4392
account_type           5
account_segment        5
dtype: int64

## 8. Remove duplicate customer records.

In [13]:
df.drop_duplicates(subset=['customer_id'],inplace=True)

In [14]:
df['customer_id'].duplicated().sum()

np.int64(0)

## 9. Standardize values in gender column.

In [15]:
df['gender'].unique()

array(['Male', 'Female', 'Other', nan], dtype=object)

## 10. Standardize values in marital_status column.

In [16]:
df['marital_status'].unique()

array(['Married', 'Single', 'Divorced', 'Widowed', nan], dtype=object)

In [18]:
dfc=df.copy()

# Missing Value Handling

## 11. Fill missing values in gender using mode.

In [7]:
df['gender'].isnull().sum()

np.int64(117)

In [8]:
df['gender']=df['gender'].fillna(df['gender'].mode()[0])

In [9]:
df['gender'].isnull().sum()

np.int64(0)

## 12. Fill missing values in marital_status using mode

In [10]:
df['marital_status'].isnull().sum()

np.int64(295)

In [11]:
df['marital_status']=df.groupby('gender')['marital_status'].transform(lambda x: x.fillna(x.mode()[0]) if not x.mode().empty else np.nan)

In [12]:
df['marital_status'].isnull().sum()

np.int64(0)

## 13. Fill missing values in annual_income using median.

In [13]:
df['annual_income'].isnull().sum()

np.int64(202)

In [14]:
df['annual_income']=df.groupby('account_type')['annual_income'].transform(lambda x: x.fillna(x.median()))

In [15]:
df['annual_income'].isnull().sum()

np.int64(0)

## 14. Fill missing values in balance using median.

In [18]:
df['balance'].isnull().sum()

np.int64(303)

In [20]:
df['balance']=df.groupby('account_type')['balance'].transform(lambda x: x.fillna(x.median()))

In [21]:
df['balance'].isnull().sum()

np.int64(0)

## 15. Fill missing values in credit_score using median.

In [22]:
df['credit_score'].isnull().sum()

np.int64(301)

In [24]:
df['credit_score']=df.groupby('account_type')['credit_score'].transform(lambda x: x.fillna(x.median()))

In [25]:
df['credit_score'].isnull().sum()

np.int64(0)

## 16. Fill missing values in monthly_txn_count using median.

In [27]:
df['monthly_txn_count'].isnull().sum()

np.int64(200)

In [28]:
df['monthly_txn_count']=df.groupby('account_type')['monthly_txn_count'].transform(lambda x: x.fillna(x.median()))

In [29]:
df['monthly_txn_count'].isnull().sum()

np.int64(0)

## 17. Fill missing values in nps_score using NumPy nanmedian().

In [31]:
df['nps_score']=df['nps_score'].fillna(np.nanmedian(df['nps_score']))

In [32]:
df['nps_score'].isnull().sum()

np.int64(0)

## 18. Fill missing values in csat_score using median.

In [35]:
df['csat_score'].isnull().sum()

np.int64(410)

In [36]:
df['csat_score']=df['csat_score'].fillna(np.nanmedian(df['csat_score']))

In [37]:
df['csat_score'].isnull().sum()

np.int64(0)

In [54]:
df.isnull().sum()

customer_id                  0
age                          0
gender                       0
state                        0
city                         0
pin_code                     0
marital_status               0
education                    0
occupation                   0
join_date                    0
tenure_years                 0
account_type                 0
account_segment              0
annual_income                0
balance                      0
credit_score                 0
num_products                 0
has_credit_card              0
has_loan                     0
has_insurance                0
has_demat                    0
has_mutual_fund              0
loan_amount                  0
loan_emi                     0
credit_limit                 0
credit_utilization_pct       0
monthly_txn_count            0
monthly_debit_amt            0
monthly_credit_amt           0
avg_txn_value                0
online_txn_pct               0
atm_withdrawal_freq          0
upi_txn_count                0
net_banking_logins           0
mobile_app_logins            0
branch_visits                0
complaints_last_year         0
complaint_resolved        5627
nps_score                    0
csat_score                   0
days_since_last_txn          0
days_since_last_login        0
is_dormant                   0
inactive_6m                  0
churn                        0
dtype: int64

In [57]:
df['complaint_resolved'].unique()

array([nan,  1.,  0.])

In [69]:
df['complaint_resolved']=df['complaint_resolved'].astype(str).str.replace('.','0')

In [70]:
df['complaint_resolved'].unique()

array(['nan', '10', '00'], dtype=object)

In [71]:
# Yes=1,No=0

In [72]:
a={'10':'yes','00':'no'}

In [76]:
#df['complaint_resolved']=df['complaint_resolved'].replace(a)

In [79]:
df['complaint_resolved'].unique()

array(['nan', 'yes', 'no'], dtype=object)

In [81]:
df['complaints_resolved']=df.groupby('complaints_last_year')['complaint_resolved'].transform(lambda x:x.fillna(x.mode()[0]) if not x.mode().empty else np.nan)

In [82]:
df['complaints_resolved'].isnull().sum()

np.int64(0)

In [84]:
df.isnull().sum()

customer_id               0
age                       0
gender                    0
state                     0
city                      0
pin_code                  0
marital_status            0
education                 0
occupation                0
join_date                 0
tenure_years              0
account_type              0
account_segment           0
annual_income             0
balance                   0
credit_score              0
num_products              0
has_credit_card           0
has_loan                  0
has_insurance             0
has_demat                 0
has_mutual_fund           0
loan_amount               0
loan_emi                  0
credit_limit              0
credit_utilization_pct    0
monthly_txn_count         0
monthly_debit_amt         0
monthly_credit_amt        0
avg_txn_value             0
online_txn_pct            0
atm_withdrawal_freq       0
upi_txn_count             0
net_banking_logins        0
mobile_app_logins         0
branch_visits             0
complaints_last_year      0
complaint_resolved        0
nps_score                 0
csat_score                0
days_since_last_txn       0
days_since_last_login     0
is_dormant                0
inactive_6m               0
churn                     0
complaints_resolved       0
dtype: int64

# Advanced Cleaning Tasks

## 31. Find customers whose age is below 18 or above 100.

In [85]:
df[(df['age']<18)|(df['age']>100)]

Empty DataFrame
Columns: [customer_id, age, gender, state, city, pin_code, marital_status, education, occupation, join_date, tenure_years, account_type, account_segment, annual_income, balance, credit_score, num_products, has_credit_card, has_loan, has_insurance, has_demat, has_mutual_fund, loan_amount, loan_emi, credit_limit, credit_utilization_pct, monthly_txn_count, monthly_debit_amt, monthly_credit_amt, avg_txn_value, online_txn_pct, atm_withdrawal_freq, upi_txn_count, net_banking_logins, mobile_app_logins, branch_visits, complaints_last_year, complaint_resolved, nps_score, csat_score, days_since_last_txn, days_since_last_login, is_dormant, inactive_6m, churn, complaints_resolved]
Index: []

[0 rows x 46 columns]

In [86]:
df[df['age']<18]

Empty DataFrame
Columns: [customer_id, age, gender, state, city, pin_code, marital_status, education, occupation, join_date, tenure_years, account_type, account_segment, annual_income, balance, credit_score, num_products, has_credit_card, has_loan, has_insurance, has_demat, has_mutual_fund, loan_amount, loan_emi, credit_limit, credit_utilization_pct, monthly_txn_count, monthly_debit_amt, monthly_credit_amt, avg_txn_value, online_txn_pct, atm_withdrawal_freq, upi_txn_count, net_banking_logins, mobile_app_logins, branch_visits, complaints_last_year, complaint_resolved, nps_score, csat_score, days_since_last_txn, days_since_last_login, is_dormant, inactive_6m, churn, complaints_resolved]
Index: []

[0 rows x 46 columns]

In [87]:
df[df['age']>100]

Empty DataFrame
Columns: [customer_id, age, gender, state, city, pin_code, marital_status, education, occupation, join_date, tenure_years, account_type, account_segment, annual_income, balance, credit_score, num_products, has_credit_card, has_loan, has_insurance, has_demat, has_mutual_fund, loan_amount, loan_emi, credit_limit, credit_utilization_pct, monthly_txn_count, monthly_debit_amt, monthly_credit_amt, avg_txn_value, online_txn_pct, atm_withdrawal_freq, upi_txn_count, net_banking_logins, mobile_app_logins, branch_visits, complaints_last_year, complaint_resolved, nps_score, csat_score, days_since_last_txn, days_since_last_login, is_dormant, inactive_6m, churn, complaints_resolved]
Index: []

[0 rows x 46 columns]

## 32. Replace invalid ages with median age.

In [89]:
df['age'].unique()

array([36, 28, 30, 24, 53, 21, 50, 41, 58, 27, 34, 32, 33, 29, 45, 31, 35,
       40, 55, 23, 52, 59, 37, 39, 42, 19, 26, 49, 57, 48, 56, 18, 20, 44,
       61, 66, 62, 38, 43, 25, 63, 46, 47, 77, 54, 69, 75, 51, 60, 82, 22,
       70, 64, 67, 73, 76, 68, 65, 74, 81, 71, 72, 78, 80, 83, 85, 79, 84])

## 33. Find negative values in financial columns.

In [93]:
df.columns

Index(['customer_id', 'age', 'gender', 'state', 'city', 'pin_code',
       'marital_status', 'education', 'occupation', 'join_date',
       'tenure_years', 'account_type', 'account_segment', 'annual_income',
       'balance', 'credit_score', 'num_products', 'has_credit_card',
       'has_loan', 'has_insurance', 'has_demat', 'has_mutual_fund',
       'loan_amount', 'loan_emi', 'credit_limit', 'credit_utilization_pct',
       'monthly_txn_count', 'monthly_debit_amt', 'monthly_credit_amt',
       'avg_txn_value', 'online_txn_pct', 'atm_withdrawal_freq',
       'upi_txn_count', 'net_banking_logins', 'mobile_app_logins',
       'branch_visits', 'complaints_last_year', 'complaint_resolved',
       'nps_score', 'csat_score', 'days_since_last_txn',
       'days_since_last_login', 'is_dormant', 'inactive_6m', 'churn',
       'complaints_resolved'],
      dtype='object')

In [101]:
# annual_income, balance, loan_amount, loan_emi, credit_limit, avg_txn_value','monthly_credit_amt', 'monthly_txn_count', 'monthly_debit_amt'

In [95]:
df[df['annual_income']<0]

Empty DataFrame
Columns: [customer_id, age, gender, state, city, pin_code, marital_status, education, occupation, join_date, tenure_years, account_type, account_segment, annual_income, balance, credit_score, num_products, has_credit_card, has_loan, has_insurance, has_demat, has_mutual_fund, loan_amount, loan_emi, credit_limit, credit_utilization_pct, monthly_txn_count, monthly_debit_amt, monthly_credit_amt, avg_txn_value, online_txn_pct, atm_withdrawal_freq, upi_txn_count, net_banking_logins, mobile_app_logins, branch_visits, complaints_last_year, complaint_resolved, nps_score, csat_score, days_since_last_txn, days_since_last_login, is_dormant, inactive_6m, churn, complaints_resolved]
Index: []

[0 rows x 46 columns]

In [96]:
df[df['balance']<0]

Empty DataFrame
Columns: [customer_id, age, gender, state, city, pin_code, marital_status, education, occupation, join_date, tenure_years, account_type, account_segment, annual_income, balance, credit_score, num_products, has_credit_card, has_loan, has_insurance, has_demat, has_mutual_fund, loan_amount, loan_emi, credit_limit, credit_utilization_pct, monthly_txn_count, monthly_debit_amt, monthly_credit_amt, avg_txn_value, online_txn_pct, atm_withdrawal_freq, upi_txn_count, net_banking_logins, mobile_app_logins, branch_visits, complaints_last_year, complaint_resolved, nps_score, csat_score, days_since_last_txn, days_since_last_login, is_dormant, inactive_6m, churn, complaints_resolved]
Index: []

[0 rows x 46 columns]

In [97]:
df[df['loan_amount']<0]

Empty DataFrame
Columns: [customer_id, age, gender, state, city, pin_code, marital_status, education, occupation, join_date, tenure_years, account_type, account_segment, annual_income, balance, credit_score, num_products, has_credit_card, has_loan, has_insurance, has_demat, has_mutual_fund, loan_amount, loan_emi, credit_limit, credit_utilization_pct, monthly_txn_count, monthly_debit_amt, monthly_credit_amt, avg_txn_value, online_txn_pct, atm_withdrawal_freq, upi_txn_count, net_banking_logins, mobile_app_logins, branch_visits, complaints_last_year, complaint_resolved, nps_score, csat_score, days_since_last_txn, days_since_last_login, is_dormant, inactive_6m, churn, complaints_resolved]
Index: []

[0 rows x 46 columns]

In [98]:
df[df['loan_emi']<0]

Empty DataFrame
Columns: [customer_id, age, gender, state, city, pin_code, marital_status, education, occupation, join_date, tenure_years, account_type, account_segment, annual_income, balance, credit_score, num_products, has_credit_card, has_loan, has_insurance, has_demat, has_mutual_fund, loan_amount, loan_emi, credit_limit, credit_utilization_pct, monthly_txn_count, monthly_debit_amt, monthly_credit_amt, avg_txn_value, online_txn_pct, atm_withdrawal_freq, upi_txn_count, net_banking_logins, mobile_app_logins, branch_visits, complaints_last_year, complaint_resolved, nps_score, csat_score, days_since_last_txn, days_since_last_login, is_dormant, inactive_6m, churn, complaints_resolved]
Index: []

[0 rows x 46 columns]

In [99]:
df[df['credit_limit']<0]

Empty DataFrame
Columns: [customer_id, age, gender, state, city, pin_code, marital_status, education, occupation, join_date, tenure_years, account_type, account_segment, annual_income, balance, credit_score, num_products, has_credit_card, has_loan, has_insurance, has_demat, has_mutual_fund, loan_amount, loan_emi, credit_limit, credit_utilization_pct, monthly_txn_count, monthly_debit_amt, monthly_credit_amt, avg_txn_value, online_txn_pct, atm_withdrawal_freq, upi_txn_count, net_banking_logins, mobile_app_logins, branch_visits, complaints_last_year, complaint_resolved, nps_score, csat_score, days_since_last_txn, days_since_last_login, is_dormant, inactive_6m, churn, complaints_resolved]
Index: []

[0 rows x 46 columns]

In [100]:
df[df['avg_txn_value']<0]

Empty DataFrame
Columns: [customer_id, age, gender, state, city, pin_code, marital_status, education, occupation, join_date, tenure_years, account_type, account_segment, annual_income, balance, credit_score, num_products, has_credit_card, has_loan, has_insurance, has_demat, has_mutual_fund, loan_amount, loan_emi, credit_limit, credit_utilization_pct, monthly_txn_count, monthly_debit_amt, monthly_credit_amt, avg_txn_value, online_txn_pct, atm_withdrawal_freq, upi_txn_count, net_banking_logins, mobile_app_logins, branch_visits, complaints_last_year, complaint_resolved, nps_score, csat_score, days_since_last_txn, days_since_last_login, is_dormant, inactive_6m, churn, complaints_resolved]
Index: []

[0 rows x 46 columns]

In [102]:
df[df['monthly_credit_amt']<0]

Empty DataFrame
Columns: [customer_id, age, gender, state, city, pin_code, marital_status, education, occupation, join_date, tenure_years, account_type, account_segment, annual_income, balance, credit_score, num_products, has_credit_card, has_loan, has_insurance, has_demat, has_mutual_fund, loan_amount, loan_emi, credit_limit, credit_utilization_pct, monthly_txn_count, monthly_debit_amt, monthly_credit_amt, avg_txn_value, online_txn_pct, atm_withdrawal_freq, upi_txn_count, net_banking_logins, mobile_app_logins, branch_visits, complaints_last_year, complaint_resolved, nps_score, csat_score, days_since_last_txn, days_since_last_login, is_dormant, inactive_6m, churn, complaints_resolved]
Index: []

[0 rows x 46 columns]

In [103]:
df[df['monthly_txn_count']<0]

Empty DataFrame
Columns: [customer_id, age, gender, state, city, pin_code, marital_status, education, occupation, join_date, tenure_years, account_type, account_segment, annual_income, balance, credit_score, num_products, has_credit_card, has_loan, has_insurance, has_demat, has_mutual_fund, loan_amount, loan_emi, credit_limit, credit_utilization_pct, monthly_txn_count, monthly_debit_amt, monthly_credit_amt, avg_txn_value, online_txn_pct, atm_withdrawal_freq, upi_txn_count, net_banking_logins, mobile_app_logins, branch_visits, complaints_last_year, complaint_resolved, nps_score, csat_score, days_since_last_txn, days_since_last_login, is_dormant, inactive_6m, churn, complaints_resolved]
Index: []

[0 rows x 46 columns]

In [104]:
df[df['monthly_debit_amt']<0]

Empty DataFrame
Columns: [customer_id, age, gender, state, city, pin_code, marital_status, education, occupation, join_date, tenure_years, account_type, account_segment, annual_income, balance, credit_score, num_products, has_credit_card, has_loan, has_insurance, has_demat, has_mutual_fund, loan_amount, loan_emi, credit_limit, credit_utilization_pct, monthly_txn_count, monthly_debit_amt, monthly_credit_amt, avg_txn_value, online_txn_pct, atm_withdrawal_freq, upi_txn_count, net_banking_logins, mobile_app_logins, branch_visits, complaints_last_year, complaint_resolved, nps_score, csat_score, days_since_last_txn, days_since_last_login, is_dormant, inactive_6m, churn, complaints_resolved]
Index: []

[0 rows x 46 columns]

## 35. Find rows where credit_utilization_pct is below 0 or above 100.

In [109]:
df[(df['credit_utilization_pct']<0)|(df['credit_utilization_pct']>100)]

Empty DataFrame
Columns: [customer_id, age, gender, state, city, pin_code, marital_status, education, occupation, join_date, tenure_years, account_type, account_segment, annual_income, balance, credit_score, num_products, has_credit_card, has_loan, has_insurance, has_demat, has_mutual_fund, loan_amount, loan_emi, credit_limit, credit_utilization_pct, monthly_txn_count, monthly_debit_amt, monthly_credit_amt, avg_txn_value, online_txn_pct, atm_withdrawal_freq, upi_txn_count, net_banking_logins, mobile_app_logins, branch_visits, complaints_last_year, complaint_resolved, nps_score, csat_score, days_since_last_txn, days_since_last_login, is_dormant, inactive_6m, churn, complaints_resolved]
Index: []

[0 rows x 46 columns]

In [110]:
df[df['credit_utilization_pct']<0]

Empty DataFrame
Columns: [customer_id, age, gender, state, city, pin_code, marital_status, education, occupation, join_date, tenure_years, account_type, account_segment, annual_income, balance, credit_score, num_products, has_credit_card, has_loan, has_insurance, has_demat, has_mutual_fund, loan_amount, loan_emi, credit_limit, credit_utilization_pct, monthly_txn_count, monthly_debit_amt, monthly_credit_amt, avg_txn_value, online_txn_pct, atm_withdrawal_freq, upi_txn_count, net_banking_logins, mobile_app_logins, branch_visits, complaints_last_year, complaint_resolved, nps_score, csat_score, days_since_last_txn, days_since_last_login, is_dormant, inactive_6m, churn, complaints_resolved]
Index: []

[0 rows x 46 columns]

In [111]:
df[df['credit_utilization_pct']>100]

Empty DataFrame
Columns: [customer_id, age, gender, state, city, pin_code, marital_status, education, occupation, join_date, tenure_years, account_type, account_segment, annual_income, balance, credit_score, num_products, has_credit_card, has_loan, has_insurance, has_demat, has_mutual_fund, loan_amount, loan_emi, credit_limit, credit_utilization_pct, monthly_txn_count, monthly_debit_amt, monthly_credit_amt, avg_txn_value, online_txn_pct, atm_withdrawal_freq, upi_txn_count, net_banking_logins, mobile_app_logins, branch_visits, complaints_last_year, complaint_resolved, nps_score, csat_score, days_since_last_txn, days_since_last_login, is_dormant, inactive_6m, churn, complaints_resolved]
Index: []

[0 rows x 46 columns]

## 36. Validate join_date and identify future dates.

In [113]:
df['join_date'].dtype

dtype('O')

In [115]:
df['join_date']=pd.to_datetime(df['join_date'])

C:\Users\Admin\AppData\Local\Temp\ipykernel_2276\2577087914.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['join_date']=pd.to_datetime(df['join_date'])

In [117]:
print(df['join_date'].dtype)

datetime64[ns]

In [118]:
df[df['join_date'] > pd.Timestamp.today()]

Empty DataFrame
Columns: [customer_id, age, gender, state, city, pin_code, marital_status, education, occupation, join_date, tenure_years, account_type, account_segment, annual_income, balance, credit_score, num_products, has_credit_card, has_loan, has_insurance, has_demat, has_mutual_fund, loan_amount, loan_emi, credit_limit, credit_utilization_pct, monthly_txn_count, monthly_debit_amt, monthly_credit_amt, avg_txn_value, online_txn_pct, atm_withdrawal_freq, upi_txn_count, net_banking_logins, mobile_app_logins, branch_visits, complaints_last_year, complaint_resolved, nps_score, csat_score, days_since_last_txn, days_since_last_login, is_dormant, inactive_6m, churn, complaints_resolved]
Index: []

[0 rows x 46 columns]

## 39. Find inconsistent loan records where has_loan = 0 but loan_amount > 0.

In [119]:
df[(df['has_loan']==0)&(df['loan_amount']>0)]

Empty DataFrame
Columns: [customer_id, age, gender, state, city, pin_code, marital_status, education, occupation, join_date, tenure_years, account_type, account_segment, annual_income, balance, credit_score, num_products, has_credit_card, has_loan, has_insurance, has_demat, has_mutual_fund, loan_amount, loan_emi, credit_limit, credit_utilization_pct, monthly_txn_count, monthly_debit_amt, monthly_credit_amt, avg_txn_value, online_txn_pct, atm_withdrawal_freq, upi_txn_count, net_banking_logins, mobile_app_logins, branch_visits, complaints_last_year, complaint_resolved, nps_score, csat_score, days_since_last_txn, days_since_last_login, is_dormant, inactive_6m, churn, complaints_resolved]
Index: []

[0 rows x 46 columns]

## 40. Find complaint records where complaint_resolved = yes but complaints_last_year = 0.

In [121]:
df[(df['complaint_resolved']=='yes')&(df['complaints_last_year']==0)]

Empty DataFrame
Columns: [customer_id, age, gender, state, city, pin_code, marital_status, education, occupation, join_date, tenure_years, account_type, account_segment, annual_income, balance, credit_score, num_products, has_credit_card, has_loan, has_insurance, has_demat, has_mutual_fund, loan_amount, loan_emi, credit_limit, credit_utilization_pct, monthly_txn_count, monthly_debit_amt, monthly_credit_amt, avg_txn_value, online_txn_pct, atm_withdrawal_freq, upi_txn_count, net_banking_logins, mobile_app_logins, branch_visits, complaints_last_year, complaint_resolved, nps_score, csat_score, days_since_last_txn, days_since_last_login, is_dormant, inactive_6m, churn, complaints_resolved]
Index: []

[0 rows x 46 columns]

In [122]:
df.to_csv('Bank churn cleaned.csv',index=False)

In [123]:
df.isnull().sum()

customer_id               0
age                       0
gender                    0
state                     0
city                      0
pin_code                  0
marital_status            0
education                 0
occupation                0
join_date                 0
tenure_years              0
account_type              0
account_segment           0
annual_income             0
balance                   0
credit_score              0
num_products              0
has_credit_card           0
has_loan                  0
has_insurance             0
has_demat                 0
has_mutual_fund           0
loan_amount               0
loan_emi                  0
credit_limit              0
credit_utilization_pct    0
monthly_txn_count         0
monthly_debit_amt         0
monthly_credit_amt        0
avg_txn_value             0
online_txn_pct            0
atm_withdrawal_freq       0
upi_txn_count             0
net_banking_logins        0
mobile_app_logins         0
branch_visits             0
complaints_last_year      0
complaint_resolved        0
nps_score                 0
csat_score                0
days_since_last_txn       0
days_since_last_login     0
is_dormant                0
inactive_6m               0
churn                     0
complaints_resolved       0
dtype: int64