In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
df=pd.read_csv(r'D:\TUFEL\Data scientist pro\Data analysis project\1 Full Projects\Employee Data\employee_data_dirty.csv')

# Data Understanding

## 1.	Check the shape of the dataset.

In [9]:
df.shape

(2040, 30)

## 2.	Display all column names.

In [16]:
pd.DataFrame(df.columns,columns=['col_names'])

               col_names
0            employee_id
1              full_name
2                    age
3                 gender
4                  email
5                  phone
6                   city
7                country
8             department
9              job_title
10       employment_type
11       education_level
12             join_date
13             exit_date
14   years_of_experience
15         annual_salary
16      bonus_percentage
17    performance_rating
18             nps_score
19    projects_completed
20        training_hours
21           remote_work
22   last_promotion_year
23            manager_id
24             team_size
25  monthly_leaves_taken
26        attrition_risk
27       salary_currency
28      linkedin_profile
29     contract_end_date

## 3.	Check the data type of each column.

In [17]:
df.dtypes

employee_id              object
full_name                object
age                     float64
gender                   object
email                    object
phone                    object
city                     object
country                  object
department               object
job_title                object
employment_type          object
education_level          object
join_date                object
exit_date                object
years_of_experience       int64
annual_salary            object
bonus_percentage        float64
performance_rating       object
nps_score               float64
projects_completed        int64
training_hours          float64
remote_work              object
last_promotion_year     float64
manager_id               object
team_size               float64
monthly_leaves_taken    float64
attrition_risk           object
salary_currency          object
linkedin_profile         object
contract_end_date        object
dtype: object

## 4.	Calculate the number of missing values in each column.

In [18]:
df.isnull().sum()

employee_id                0
full_name                 52
age                       73
gender                    68
email                     41
phone                    355
city                       0
country                    0
department                 0
job_title                  0
employment_type           71
education_level            0
join_date                  0
exit_date               1621
years_of_experience        0
annual_salary             29
bonus_percentage          80
performance_rating        64
nps_score                 69
projects_completed         0
training_hours            79
remote_work               29
last_promotion_year      199
manager_id               117
team_size                113
monthly_leaves_taken     101
attrition_risk             0
salary_currency           98
linkedin_profile         296
contract_end_date       1485
dtype: int64

## 5.	Calculate the percentage of missing values column-wise.

In [20]:
round(df.isnull().sum()/len(df)*100,2)

employee_id              0.00
full_name                2.55
age                      3.58
gender                   3.33
email                    2.01
phone                   17.40
city                     0.00
country                  0.00
department               0.00
job_title                0.00
employment_type          3.48
education_level          0.00
join_date                0.00
exit_date               79.46
years_of_experience      0.00
annual_salary            1.42
bonus_percentage         3.92
performance_rating       3.14
nps_score                3.38
projects_completed       0.00
training_hours           3.87
remote_work              1.42
last_promotion_year      9.75
manager_id               5.74
team_size                5.54
monthly_leaves_taken     4.95
attrition_risk           0.00
salary_currency          4.80
linkedin_profile        14.51
contract_end_date       72.79
dtype: float64

## 6.	Identify duplicate rows.

In [23]:
df[df.duplicated()]
df.duplicated().sum()

np.int64(40)

## 7.	Check whether employee_id contains duplicates.

In [26]:
df[df['employee_id'].duplicated(keep=False)]

,employee_id,full_name,age,gender,email,phone,city,country,department,job_title,...,training_hours,remote_work,last_promotion_year,manager_id,team_size,monthly_leaves_taken,attrition_risk,salary_currency,linkedin_profile,contract_end_date
0,EMP3387,Neha Patel,37.0,Non-Binary,neha.patel@company.in,-7545786564,Mumbai,India,Marketing,SEO Specialist,...,129.42,TRUE,2024.0,EMP1010,14.0,1.2,High,AUD,linkedin.com/in/nehapatel373,08-10-2026
1,EMP2682,Ava Reddy,25.0,Prefer not to say,ava.reddy@yahoo.com,(957) 427-1356,Sydney,Australia,Product,Senior PM,...,62.98,FALSE,NaN,EMP2233,12.0,0.9,Medium,CAD,linkedin.com/in/avareddy878,NaN
3,EMP1915,Amelia Bose,45.0,Prefer not to say,amelia.bose@hotmail.com,-7968601888,Bangalore,India,Engineering,Engineering Manager,...,166.99,TRUE,2022.0,EMP1772,1.0,1.7,High,CAD,linkedin.com/in/ameliabose880,27-03-2025
6,EMP1815,Rajesh Miller,57.0,Prefer not to say,rajesh.miller@gmail.com,(232) 622-2191,Singapore,Singapore,Customer Support,Team Lead,...,94.86,FALSE,NaN,EMP2166,17.0,1.3,Medium,USD,linkedin.com/in/rajeshmiller864,NaN
7,EMP3677,Rahul Verma,35.0,Non-Binary,rahul.verma@yahoo.com,9359871900,Pune,India,HR,HR Executive,...,124.79,TRUE,NaN,EMP3938,18.0,2.4,Low,CAD,linkedin.com/in/rahulverma151,27-06-2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2034,EMP3704,Anjali Williams,45.0,Prefer not to say,anjali.williams@gmail.com,9412363442,Pune,India,Operations,Logistics Coordinator,...,48.06,FALSE,2013.0,EMP3371,8.0,4.1,Low,GBP,linkedin.com/in/anjaliwilliams937,NaN
2036,EMP1915,Charlotte Iyer,58.0,Female,charlotte.iyer@hotmail.com,-6956,San Francisco,USA,engeneering,HR Manager,...,177.32,TRUE,2019.0,EMP3897,9.0,4.8,Low,GBP,linkedin.com/in/charlotteiyer400,NaN
2037,EMP2809,Jackson Johnson,43.0,F,jackson.johnson@yahoo.com,-2228,New York,USA,Finance,Finance Manager,...,25.56,TRUE,NaN,EMP1705,13.0,0.4,Low,USD,linkedin.com/in/jacksonjohnson654,NaN
2038,EMP2323,Arjun Miller,33.0,Prefer not to say,arjun.miller@outlook.com,9421402810,Pune,India,Product,Product Manager,...,168.34,FALSE,2020.0,EMP3073,11.0,4.9,Low,INR,linkedin.com/in/arjunmiller688,NaN
2039,EMP2049,Charlotte Verma,31.0,Non-Binary,charlotte@verma,NaN,Dubai,UAE,Product,Product Analyst,...,189.13,FALSE,2013.0,EMP1479,5.0,3.9,Medium,CAD,linkedin.com/in/charlotteverma297,NaN

## 8.	Count unique values in each categorical column.

In [28]:
df.select_dtypes(include='object').nunique()

employee_id           1386
full_name             1075
gender                   9
email                 1763
phone                 1626
city                    15
country                  7
department              16
job_title               50
employment_type          4
education_level          9
join_date             1754
exit_date              362
annual_salary         1935
performance_rating      13
remote_work              8
manager_id            1398
attrition_risk           6
salary_currency          5
linkedin_profile      1705
contract_end_date      436
dtype: int64

## 9.	Display unique values for important categorical columns such as Gender, Department, City, and Country.

In [32]:
df

,employee_id,full_name,age,gender,email,phone,city,country,department,job_title,...,training_hours,remote_work,last_promotion_year,manager_id,team_size,monthly_leaves_taken,attrition_risk,salary_currency,linkedin_profile,contract_end_date
0,EMP3387,Neha Patel,37.0,Non-Binary,neha.patel@company.in,-7545786564,Mumbai,India,Marketing,SEO Specialist,...,129.42,TRUE,2024.0,EMP1010,14.0,1.2,High,AUD,linkedin.com/in/nehapatel373,08-10-2026
1,EMP2682,Ava Reddy,25.0,Prefer not to say,ava.reddy@yahoo.com,(957) 427-1356,Sydney,Australia,Product,Senior PM,...,62.98,FALSE,NaN,EMP2233,12.0,0.9,Medium,CAD,linkedin.com/in/avareddy878,NaN
2,EMP1964,Aarav Moore,51.0,Prefer not to say,aarav.moore@gmail.com,NaN,Kolkata,India,Product,Group PM,...,175.35,FALSE,2023.0,EMP1532,14.0,1.6,High,USD,linkedin.com/in/aaravmoore847,NaN
3,EMP1915,Amelia Bose,45.0,Prefer not to say,amelia.bose@hotmail.com,-7968601888,Bangalore,India,Engineering,Engineering Manager,...,166.99,TRUE,2022.0,EMP1772,1.0,1.7,High,CAD,linkedin.com/in/ameliabose880,27-03-2025
4,EMP1851,Divya Singh,22.0,M,divya.singh@hotmail.com,9.17522E+11,Delhi,India,Finance,Finance Manager,...,2.03,TRUE,2011.0,EMP1518,16.0,0.5,High,CAD,linkedin.com/in/divyasingh970,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,EMP2340,Rajesh Wilson,27.0,Male,rajesh.wilson@corp.com,-7562033622,Dubai,UAE,Sales,Account Executive,...,131.25,TRUE,2013.0,EMP2907,19.0,2.5,Medium,USD,NaN,NaN
2036,EMP1915,Charlotte Iyer,58.0,Female,charlotte.iyer@hotmail.com,-6956,San Francisco,USA,engeneering,HR Manager,...,177.32,TRUE,2019.0,EMP3897,9.0,4.8,Low,GBP,linkedin.com/in/charlotteiyer400,NaN
2037,EMP2809,Jackson Johnson,43.0,F,jackson.johnson@yahoo.com,-2228,New York,USA,Finance,Finance Manager,...,25.56,TRUE,NaN,EMP1705,13.0,0.4,Low,USD,linkedin.com/in/jacksonjohnson654,NaN
2038,EMP2323,Arjun Miller,33.0,Prefer not to say,arjun.miller@outlook.com,9421402810,Pune,India,Product,Product Manager,...,168.34,FALSE,2020.0,EMP3073,11.0,4.9,Low,INR,linkedin.com/in/arjunmiller688,NaN
2039,EMP2049,Charlotte Verma,31.0,Non-Binary,charlotte@verma,NaN,Dubai,UAE,Product,Product Analyst,...,189.13,FALSE,2013.0,EMP1479,5.0,3.9,Medium,CAD,linkedin.com/in/charlotteverma297,NaN

In [39]:
df[['gender','department','city','country']].nunique()

gender         9
department    16
city          15
country        7
dtype: int64

In [38]:
for col in df.columns:
    print(f"\nUnique Values in {col} :")
    print(df[col].unique())

Unique Values in employee_id :
['EMP3387' 'EMP2682' 'EMP1964' ... 'EMP1420' 'EMP2694' 'EMP2340']

Unique Values in full_name :
['Neha Patel' 'Ava Reddy' 'Aarav Moore' ... 'PRIYA JONES' 'Mason Jones'
 'Jackson Johnson']

Unique Values in age :
[ 37.  25.  51.  45.  22. 393.  57.  35.  27.  43.  52.  59.  34.  42.
  49.  46.  48.  58.  nan  24.  28.  60.  56.  33.  38. 881.  50.  41.
  29.  39.  53.  30.  32.  54.  -3.  -9. 790. 538.  55.  44.  36.  47.
  23.  31.  26.  40. 534. 914.  -8.   3.   1. 285.  -5. 365. 293.  -4.
 729. 982. 503. 202.   4. 740. 455. 205. 684. 487.   0. 817. -10.  -6.
 330. 799. 627.  -2. 220. 218.  -1. 971. 267. 475. 400. 390. 609. 553.
 327. 479. 359. 886. 399.   2. 727. 724. 288. 576. 811.   5. 833. 313.
  -7. 823. 303. 532. 468. 602. 384. 930. 955. 742. 301. 780. 396. 560.
 936. 762. 545. 251. 268. 984. 983. 379. 397.]

Unique Values in gender :
['Non-Binary' 'Prefer not to say' 'M' 'Male' 'Female' nan 'F' 'FEMALE'
 'femal' 'male']

Unique Values in email :
['neha.patel@company.in' 'ava.reddy@yahoo.com' 'aarav.moore@gmail.com' ...
 'rajesh.wilson@corp.com' 'jackson.johnson@yahoo.com'
 'arjun.miller@outlook.com']

Unique Values in phone :
['-7545786564' '(957) 427-1356' nan ... '-6956' '-2228' '9421402810']

Unique Values in city :
['Mumbai' 'Sydney' 'Kolkata' 'Bangalore' 'Delhi' 'Singapore' 'Pune'
 'Hyderabad' 'San Francisco' 'Toronto' 'Ahmedabad' 'London' 'Dubai'
 'Chennai' 'New York']

Unique Values in country :
['India' 'Australia' 'Singapore' 'USA' 'Canada' 'UK' 'UAE']

Unique Values in department :
['Marketing' 'Product' 'Engineering' 'Finance' 'Customer Support' 'HR'
 'Operations' 'Legal' 'Data Science' 'Sales' 'Finace' 'HR ' 'engeneering'
 'Data science' 'Slaes' 'Engg']

Unique Values in job_title :
['SEO Specialist' 'Senior PM' 'Group PM' 'Engineering Manager'
 'Finance Manager' 'Senior Analyst' 'Team Lead' 'HR Executive'
 'Marketing Manager' 'Product Manager' 'Supply Chain Analyst'
 'Senior Counsel' 'ML Engineer' 'Senior Sales Rep' 'Senior Data Scientist'
 'Financial Analyst' 'Senior Agent' 'VP Support' 'DevOps Engineer' 'COO'
 'HR Business Partner' 'Head of Data' 'Data Analyst' 'Recruiter' 'CHRO'
 'HR Manager' 'Support Agent' 'Software Engineer' 'Marketing Analyst'
 'CMO' 'Product Analyst' 'Content Strategist' 'Controller' 'Legal Manager'
 'Ops Manager' 'Logistics Coordinator' 'VP Sales' 'Associate'
 'Data Scientist' 'CLO' 'Sales Rep' 'Account Executive' 'CPO' 'Senior SWE'
 'Support Manager' 'Legal Counsel' 'CFO' 'Lead Engineer'
 'Operations Analyst' 'Sales Manager']

Unique Values in employment_type :
['Part-Time' 'Full-Time' 'Contract' 'Intern' nan]

Unique Values in education_level :
["Master's" 'High School' 'Associate' 'PhD' 'BE/BTech' 'MCA' 'MBA' '  '
 "Bachelor's"]

Unique Values in join_date :
['17-09-2016' '08-28-2018' '25-Sep-15' ... '23-12-2022' '31-Jan-16'
 '22-Mar-10']

Unique Values in exit_date :
[nan '07-03-2023' '26-05-2023' '08-11-2021' '24-08-2023' '13-07-2022'
 '03-02-2020' '23-04-2021' '24-01-2024' '18-02-2023' '24-08-2022'
 '17-10-2020' '20-10-2021' '11-08-2023' '28-07-2024' '21-01-2024'
 '24-04-2021' '19-05-2024' '24-09-2020' '30-10-2023' '20-09-2024'
 '06-12-2024' '03-05-2024' '11-04-2021' '15-12-2024' '23-06-2020'
 '05-04-2024' '09-09-2024' '25-02-2022' '20-07-2024' '21-02-2020'
 '01-04-2022' '28-01-2024' '17-06-2023' '04-05-2024' '16-05-2024'
 '05-08-2021' '16-03-2024' '26-12-2024' '26-02-2021' '16-07-2023'
 '02-12-2020' '09-10-2020' '29-09-2021' '12-03-2021' '22-06-2020'
 '02-05-2023' '29-02-2020' '17-11-2022' '03-04-2020' '07-11-2023'
 '28-05-2024' '24-10-2023' '22-09-2020' '17-03-2024' '28-09-2021'
 '25-07-2021' '05-11-2020' '12-06-2021' '30-01-2021' '06-06-2021'
 '09-06-2023' '15-06-2022' '06-11-2024' '22-07-2024' '29-07-2024'
 '03-10-2024' '10-01-2023' '27-02-2020' '28-06-2024' '29-10-2022'
 '16-12-2023' '11-12-2021' '10-11-2023' '14-07-2024' '23-10-2023'
 '03-06-2021' '10-02-2023' '15-11-2021' '03-11-2022' '14-08-2022'
 '27-11-2024' '27-12-2020' '01-12-2024' '15-07-2020' '14-09-2021'
 '25-03-2024' '09-08-2020' '10-06-2022' '24-07-2020' '11-10-2021'
 '31-05-2022' '19-09-2022' '06-09-2020' '23-01-2021' '16-12-2021'
 '07-01-2023' '13-06-2023' '30-03-2022' '06-03-2024' '21-11-2020'
 '27-11-2022' '27-07-2024' '09-08-2023' '01-11-2021' '10-04-2024'
 '03-03-2021' '17-07-2023' '15-01-2022' '11-01-2022' '02-01-2020'
 '27-12-2024' '21-05-2021' '14-12-2020' '05-02-2023' '23-03-2021'
 '23-03-2022' '29-08-2023' '10-08-2024' '31-03-2020' '26-08-2024'
 '28-10-2022' '31-05-2021' '08-08-2024' '23-12-2020' '06-07-2021'
 '22-04-2023' '09-12-2023' '18-05-2023' '08-06-2024' '07-01-2024'
 '11-08-2020' '29-03-2023' '13-12-2023' '23-01-2020' '30-12-2020'
 '12-03-2022' '18-05-2022' '13-02-2020' '01-04-2021' '26-12-2020'
 '14-10-2020' '19-06-2020' '21-07-2021' '16-04-2021' '06-10-2023'
 '13-12-2024' '05-10-2021' '15-09-2023' '16-05-2023' '02-06-2021'
 '01-05-2022' '09-03-2020' '12-09-2023' '11-01-2021' '26-05-2020'
 '25-04-2024' '07-01-2022' '12-01-2024' '19-11-2024' '29-11-2022'
 '06-05-2020' '26-08-2021' '26-06-2022' '01-03-2021' '20-12-2020'
 '31-10-2021' '16-06-2022' '16-09-2024' '16-03-2023' '22-03-2022'
 '08-11-2024' '25-03-2023' '04-04-2022' '01-06-2024' '08-12-2023'
 '18-08-2023' '26-11-2023' '30-12-2024' '06-04-2021' '08-10-2023'
 '19-11-2023' '18-10-2021' '23-11-2021' '26-01-2020' '04-01-2024'
 '21-05-2023' '06-08-2023' '12-04-2024' '10-12-2020' '08-10-2020'
 '12-10-2022' '19-10-2023' '09-10-2021' '22-01-2022' '13-08-2021'
 '03-09-2022' '31-12-2020' '24-06-2023' '23-12-2023' '31-03-2021'
 '13-01-2024' '30-06-2022' '27-09-2021' '29-04-2024' '21-07-2020'
 '25-08-2022' '14-07-2020' '05-02-2021' '08-02-2021' '26-11-2022'
 '01-04-2024' '17-07-2021' '04-11-2022' '05-05-2023' '13-03-2024'
 '27-02-2021' '28-07-2021' '02-01-2023' '08-05-2024' '15-07-2022'
 '22-06-2023' '31-08-2024' '05-12-2023' '04-11-2020' '01-02-2022'
 '26-05-2022' '17-01-2024' '10-01-2022' '09-12-2020' '24-06-2022'
 '18-01-2023' '15-09-2024' '14-01-2023' '02-07-2021' '13-04-2022'
 '19-04-2022' '26-10-2024' '06-04-2020' '12-11-2022' '08-09-2024'
 '18-04-2024' '18-02-2024' '16-03-2021' '31-01-2021' '26-03-2020'
 '06-09-2022' '17-06-2021' '12-11-2020' '26-03-2024' '15-08-2022'
 '14-10-2021' '05-04-2020' '07-11-2020' '06-06-2023' '17-08-2023'
 '31-08-2022' '24-07-2022' '02-12-2024' '13-05-2022' '27-01-2024'
 '03-04-2022' '21-06-2021' '20-06-2020' '20-11-2024' '14-10-2022'
 '27-05-2021' '15-11-2024' '19-06-2023' '24-01-2021' '29-09-2024'
 '18-05-2021' '31-07-2022' '04-07-2021' '27-05-2024' '08-10-2022'
 '13-04-2020' '22-10-2024' '28-04-2022' '20-10-2020' '15-12-2022'
 '06-03-2020' '04-05-2021' '20-01-2020' '07-10-2023' '09-02-2022'
 '28-02-2023' '28-09-2024' '02-04-2020' '22-06-2022' '12-06-2020'
 '30-08-2024' '20-05-2020' '07-06-2020' '20-03-2021' '04-02-2024'
 '06-11-2022' '09-05-2023' '24-10-2022' '01-02-2020' '10-07-2021'
 '26-03-2022' '28-11-2021' '02-01-2024' '09-08-2024' '12-09-2020'
 '06-09-2021' '12-05-2022' '26-01-2024' '25-12-2023' '26-02-2023'
 '04-08-2021' '31-05-2023' '12-06-2023' '01-01-2023' '29-03-2021'
 '18-09-2020' '23-02-2020' '11-02-2024' '13-01-2021' '14-08-2024'
 '26-12-2021' '11-03-2021' '15-02-2024' '07-05-2021' '17-01-2020'
 '30-10-2024' '23-08-2021' '12-06-2022' '08-03-2024' '28-01-2020'
 '14-05-2023' '22-01-2023' '15-01-2024' '30-12-2021' '29-07-2021'
 '07-10-2020' '12-07-2024' '12-06-2024' '16-05-2021' '05-09-2024'
 '05-08-2024' '08-08-2020' '23-09-2020' '22-12-2023' '31-12-2021'
 '21-01-2023' '20-11-2022' '04-10-2023' '16-12-2022' '21-03-2024'
 '29-01-2021' '30-09-2021' '26-07-2023' '22-10-2021' '04-09-2022'
 '02-02-2023' '31-05-2020' '05-10-2020' '11-12-2022' '10-08-2022'
 '20-02-2023' '10-03-2024']

Unique Values in years_of_experience :
[ 7  5  8 12  2  3  0 13  6  4 11 26  1  9 10 19 17 22 -1 -2 16 15 20 30
 14 24 21 23 27 18 28 -3 25 29]

Unique Values in annual_salary :
['1295098' '1430387' '1889444' ... '1470895' '1147268' 'â‚¹804,630']

Unique Values in bonus_percentage :
[39.75 13.08 20.25 ...  7.79 12.4   7.2 ]

Unique Values in performance_rating :
['Average' 'Outstanding' 'Good' 'Below Average' 'Excellent' '4' nan '5'
 '1' '2' 'avg' 'GOOD' '3' 'excellent']

Unique Values in nps_score :
[  0.  nan   7.   2.   5.  10.  60.   9.   3.   4.   6.  76.   8.   1.
  62.  96.  27.  98.  91.  15.  92.  35.  81.  70.  78.  53.  16.  29.
  58.  69.  26. 100.  31.  49.  11.  80.  54.  61.  68.  41.  93.  47.
  17.  23.  12.  22.  24.  75.  67.  84.  32.  95.  28.  77.  48.  55.
  33.  87.  82.  42.  18.  57.  72.  52.  71.  97.  66.  43.]

Unique Values in projects_completed :
[ 36  26  21  -1  10  30  22  50   2  -6  33   0  15  41  18  -4  35  12
   4   6   1  42  19  34  32  38  47   8  44  39  45  43  25  20  23   9
  49  16  37   7  -3  29  31  14  46  48   3  24  17  -7  13  40  28  11
  -5  27   5 -10  -9  -8  -2]

Unique Values in training_hours :
[129.42  62.98 175.35 ... 177.32  25.56 189.13]

Unique Values in remote_work :
['TRUE' 'FALSE' nan 'yes' '0' 'Yes' '1' 'No' 'no']

Unique Values in last_promotion_year :
[2024.   nan 2023. 2022. 2011. 2013. 2010. 2019. 2016. 2014. 2017. 2021.
 2015. 2018. 2020. 2012.]

Unique Values in manager_id :
['EMP1010' 'EMP2233' 'EMP1532' ... 'EMP3371' 'EMP3073' 'EMP1479']

Unique Values in team_size :
[14. 12.  1. 16.  4. 17. 18. 15.  7. nan  6. 19. 11.  9.  3.  2.  8. 20.
  5. 13. 10.]

Unique Values in monthly_leaves_taken :
[1.2 0.9 1.6 1.7 0.5 2.3 1.3 2.4 3.4 2.1 4.1 0.7 4.7 4.5 1.5 4.6 4.  3.3
 2.7 nan 4.4 1.1 0.4 3.  2.  4.9 5.  3.6 0.3 1.8 2.5 2.9 4.3 4.8 3.2 4.2
 2.2 3.8 1.9 2.6 3.5 3.9 3.1 2.8 0.8 1.  1.4 0.6 0.  0.1 0.2 3.7]

Unique Values in attrition_risk :
['High' 'Medium' 'Low' 'med' 'low' 'HIGH']

Unique Values in salary_currency :
['AUD' 'CAD' 'USD' 'INR' 'GBP' nan]

Unique Values in linkedin_profile :
['linkedin.com/in/nehapatel373' 'linkedin.com/in/avareddy878'
 'linkedin.com/in/aaravmoore847' ... 'linkedin.com/in/jacksonjohnson654'
 'linkedin.com/in/arjunmiller688' 'linkedin.com/in/charlotteverma297']

Unique Values in contract_end_date :
['08-10-2026' nan '27-03-2025' '27-06-2025' '13-07-2024' '17-07-2025'
 '26-01-2024' '22-07-2025' '23-09-2026' '16-12-2024' '04-08-2025'
 '04-09-2024' '08-02-2026' '06-08-2024' '08-01-2025' '14-05-2025'
 '27-09-2025' '20-07-2026' '21-02-2025' '22-04-2026' '08-02-2024'
 '25-06-2024' '09-05-2026' '13-01-2026' '16-07-2024' '19-09-2026'
 '17-03-2025' '13-12-2024' '07-09-2026' '14-09-2025' '02-12-2024'
 '29-05-2025' '18-06-2025' '01-02-2026' '09-04-2026' '18-08-2026'
 '27-07-2026' '13-07-2025' '11-07-2024' '02-04-2025' '23-07-2025'
 '15-12-2026' '04-02-2026' '21-11-2025' '24-08-2024' '24-05-2025'
 '25-06-2025' '02-04-2024' '16-03-2025' '26-05-2026' '09-11-2025'
 '03-04-2026' '17-08-2026' '19-12-2026' '25-05-2025' '18-05-2026'
 '17-03-2026' '16-10-2024' '16-06-2024' '02-02-2025' '23-07-2024'
 '21-08-2025' '31-01-2025' '26-02-2026' '13-07-2026' '03-04-2025'
 '18-08-2025' '09-12-2024' '22-11-2024' '13-08-2026' '06-12-2025'
 '30-08-2024' '18-01-2024' '31-01-2024' '11-06-2024' '01-01-2025'
 '24-07-2026' '17-10-2024' '04-04-2026' '27-08-2024' '18-02-2026'
 '29-04-2024' '25-02-2026' '07-10-2024' '31-07-2026' '14-02-2024'
 '06-11-2025' '11-05-2025' '16-04-2026' '15-10-2026' '25-09-2026'
 '24-10-2025' '28-06-2024' '12-06-2024' '02-02-2024' '26-03-2026'
 '06-04-2024' '19-06-2026' '25-06-2026' '27-01-2024' '22-01-2024'
 '08-08-2025' '29-10-2024' '01-10-2024' '17-12-2026' '10-11-2025'
 '23-12-2024' '23-12-2026' '22-04-2024' '06-11-2024' '17-12-2025'
 '16-09-2024' '18-11-2024' '17-03-2024' '10-06-2025' '04-09-2025'
 '06-04-2025' '14-06-2025' '22-02-2025' '19-02-2026' '29-07-2025'
 '19-05-2025' '19-09-2024' '26-05-2024' '30-07-2026' '15-06-2025'
 '15-01-2024' '14-11-2025' '12-06-2026' '28-06-2026' '09-04-2025'
 '07-11-2026' '26-01-2026' '24-08-2026' '04-07-2025' '07-09-2025'
 '19-01-2024' '03-01-2025' '07-03-2025' '07-03-2026' '30-06-2026'
 '15-07-2026' '19-07-2026' '03-02-2024' '13-04-2026' '02-07-2026'
 '09-08-2025' '10-09-2024' '15-03-2024' '15-09-2024' '09-06-2026'
 '07-10-2025' '29-01-2026' '23-01-2025' '08-09-2024' '27-04-2024'
 '23-08-2026' '28-02-2025' '05-01-2025' '17-05-2024' '05-07-2024'
 '02-11-2026' '28-06-2025' '14-02-2026' '10-03-2024' '01-04-2026'
 '14-05-2024' '15-05-2026' '23-01-2024' '10-08-2026' '25-02-2024'
 '12-07-2024' '10-04-2024' '20-02-2026' '19-10-2026' '17-09-2024'
 '31-08-2026' '18-09-2024' '16-03-2026' '24-07-2025' '03-03-2025'
 '19-05-2024' '14-09-2026' '24-12-2024' '23-10-2024' '01-07-2024'
 '28-09-2024' '25-04-2026' '02-09-2024' '20-07-2024' '07-06-2025'
 '13-02-2025' '01-06-2026' '12-11-2024' '30-10-2026' '20-10-2025'
 '01-06-2024' '29-11-2026' '26-12-2026' '29-12-2024' '06-08-2026'
 '29-05-2026' '29-09-2024' '14-04-2026' '29-09-2025' '08-04-2025'
 '02-01-2025' '02-03-2024' '17-04-2025' '29-08-2025' '03-05-2024'
 '07-04-2026' '22-01-2025' '22-07-2024' '29-04-2025' '05-03-2024'
 '27-12-2024' '17-12-2024' '21-03-2026' '04-10-2025' '27-05-2025'
 '24-06-2025' '07-12-2025' '03-03-2024' '26-09-2026' '08-09-2025'
 '20-08-2026' '27-10-2025' '07-04-2025' '28-12-2024' '01-09-2025'
 '15-03-2025' '14-12-2025' '24-10-2024' '10-09-2025' '09-10-2026'
 '30-03-2025' '02-06-2025' '09-01-2026' '05-08-2025' '02-11-2024'
 '15-05-2024' '05-09-2025' '09-02-2026' '21-10-2025' '09-05-2025'
 '14-12-2024' '09-09-2026' '10-01-2024' '01-08-2026' '16-12-2025'
 '06-07-2026' '15-11-2026' '29-06-2025' '30-05-2026' '15-03-2026'
 '13-06-2024' '19-01-2025' '01-10-2025' '25-10-2025' '23-08-2025'
 '08-11-2025' '02-04-2026' '10-05-2024' '13-05-2025' '25-02-2025'
 '13-05-2024' '19-02-2024' '09-07-2025' '24-07-2024' '31-05-2026'
 '08-01-2026' '24-04-2026' '09-06-2024' '19-10-2025' '25-01-2026'
 '14-10-2024' '30-06-2024' '14-03-2026' '04-12-2026' '06-02-2025'
 '31-07-2025' '14-11-2026' '29-11-2024' '21-05-2026' '26-01-2025'
 '17-11-2025' '10-01-2026' '09-01-2024' '06-07-2025' '12-02-2026'
 '05-11-2026' '15-11-2024' '14-07-2026' '16-04-2024' '05-11-2025'
 '15-05-2025' '14-03-2025' '29-12-2025' '19-08-2026' '28-12-2025'
 '25-03-2025' '21-04-2026' '28-11-2024' '17-11-2024' '17-07-2024'
 '23-10-2026' '21-03-2025' '01-02-2024' '29-08-2024' '02-10-2025'
 '05-03-2026' '02-07-2025' '01-02-2025' '03-08-2024' '10-10-2026'
 '04-09-2026' '11-04-2024' '16-05-2024' '17-01-2026' '24-01-2026'
 '24-04-2025' '16-02-2026' '22-08-2024' '25-05-2026' '07-08-2025'
 '15-01-2025' '05-11-2024' '08-03-2025' '15-02-2026' '25-09-2025'
 '09-02-2025' '02-03-2025' '26-09-2024' '07-07-2025' '19-11-2024'
 '03-02-2025' '21-09-2024' '24-01-2024' '04-12-2025' '28-09-2026'
 '06-08-2025' '13-01-2025' '29-07-2024' '03-09-2025' '24-09-2026'
 '12-09-2025' '26-03-2025' '19-06-2024' '01-10-2026' '30-08-2026'
 '10-07-2025' '31-10-2025' '15-11-2025' '02-12-2026' '02-11-2025'
 '12-07-2025' '18-12-2024' '10-12-2025' '06-06-2025' '17-11-2026'
 '22-12-2026' '29-06-2024' '25-11-2025' '19-02-2025' '17-08-2024'
 '04-04-2024' '08-06-2024' '20-12-2024' '28-12-2026' '18-03-2024'
 '05-12-2024' '06-11-2026' '07-04-2024' '24-04-2024' '06-01-2025'
 '03-12-2024' '22-09-2026' '06-10-2026' '08-05-2025' '29-06-2026'
 '01-05-2026' '21-11-2026' '12-01-2025' '08-05-2026' '28-03-2025'
 '10-02-2024' '24-05-2026' '20-06-2025' '13-03-2025' '02-05-2026'
 '04-01-2025' '26-08-2024' '21-04-2024' '15-10-2025' '06-12-2024'
 '18-05-2025' '08-09-2026' '09-07-2024' '05-12-2026' '22-12-2025'
 '14-07-2025' '11-09-2026' '24-06-2024' '17-07-2026' '18-04-2025'
 '16-09-2026' '06-03-2024' '22-05-2024' '03-06-2026' '18-07-2024'
 '23-02-2024' '17-01-2024' '23-06-2025' '04-03-2026' '02-08-2024'
 '04-05-2024' '14-04-2024' '10-07-2024' '14-01-2026' '03-05-2025'
 '13-08-2025' '08-08-2026' '16-01-2026' '21-12-2026' '10-05-2026'
 '28-05-2026' '07-05-2025' '23-10-2025' '11-06-2026' '15-06-2024'
 '11-12-2024' '11-11-2026' '15-04-2026' '02-09-2025' '28-04-2025'
 '16-08-2026']

## 10.	Create a data quality summary report.

Total Rows
Total Columns
Missing Values
Duplicate Rows
Duplicate Employee IDs
Data Types
Completeness %

In [44]:
df.columns

Index(['employee_id', 'full_name', 'age', 'gender', 'email', 'phone', 'city',
       'country', 'department', 'job_title', 'employment_type',
       'education_level', 'join_date', 'exit_date', 'years_of_experience',
       'annual_salary', 'bonus_percentage', 'performance_rating', 'nps_score',
       'projects_completed', 'training_hours', 'remote_work',
       'last_promotion_year', 'manager_id', 'team_size',
       'monthly_leaves_taken', 'attrition_risk', 'salary_currency',
       'linkedin_profile', 'contract_end_date'],
      dtype='object')

In [46]:
Report = pd.DataFrame({'Total Rows :': df.shape[0],
                      'Total Columns :': df.shape[1],
                      'Missing Values :': df.isnull().sum(),
                      'Duplicate Rows :': df.duplicated().sum(),
                      'Duplicated Employee Ids :': df['employee_id'].duplicated().sum(),
                      'Data_type :': df.dtypes})

In [47]:
Report

,Total Rows :,Total Columns :,Missing Values :,Duplicate Rows :,Duplicated Employee Ids :,Data_type :
employee_id,2040,30,0,40,654,object
full_name,2040,30,52,40,654,object
age,2040,30,73,40,654,float64
gender,2040,30,68,40,654,object
email,2040,30,41,40,654,object
phone,2040,30,355,40,654,object
city,2040,30,0,40,654,object
country,2040,30,0,40,654,object
department,2040,30,0,40,654,object
job_title,2040,30,0,40,654,object
employment_type,2040,30,71,40,654,object
education_level,2040,30,0,40,654,object
join_date,2040,30,0,40,654,object
exit_date,2040,30,1621,40,654,object
years_of_experience,2040,30,0,40,654,int64
annual_salary,2040,30,29,40,654,object
bonus_percentage,2040,30,80,40,654,float64
performance_rating,2040,30,64,40,654,object
nps_score,2040,30,69,40,654,float64
projects_completed,2040,30,0,40,654,int64
training_hours,2040,30,79,40,654,float64
remote_work,2040,30,29,40,654,object
last_promotion_year,2040,30,199,40,654,float64
manager_id,2040,30,117,40,654,object
team_size,2040,30,113,40,654,float64
monthly_leaves_taken,2040,30,101,40,654,float64
attrition_risk,2040,30,0,40,654,object
salary_currency,2040,30,98,40,654,object
linkedin_profile,2040,30,296,40,654,object
contract_end_date,2040,30,1485,40,654,object

# Phase 2: Missing Value Handling

## 11.	Fill missing values in age using the median.

In [49]:
df['age'].median()

41.0

In [51]:
df['age']=df['age'].fillna(df['age'].median())

In [52]:
df['age'].isnull().sum()

np.int64(0)

## 12.	Fill missing values in gender using the mode.

In [55]:
df['gender'].mode()

0    Prefer not to say
Name: gender, dtype: object

In [56]:
df['gender']=df['gender'].fillna(df['gender'].mode()[0])

In [57]:
df['gender'].isnull().sum()

np.int64(0)

## 13.	Fill missing values in city using the mode.

In [58]:
df['city'].mode()

0    San Francisco
Name: city, dtype: object

In [60]:
df[['city','country']]

               city    country
0            Mumbai      India
1            Sydney  Australia
2           Kolkata      India
3         Bangalore      India
4             Delhi      India
...             ...        ...
2035          Dubai        UAE
2036  San Francisco        USA
2037       New York        USA
2038           Pune      India
2039          Dubai        UAE

[2040 rows x 2 columns]

In [62]:
df['city']=df.groupby('country')['city'].transform(lambda x: x.fillna(x.mode()[0] if not x.mode().empty else np.nan))

In [65]:
df['city'].isnull().sum()

np.int64(0)

## 14.	Fill missing values in country using the mode.

In [68]:
df['country'].isnull().sum()

np.int64(0)

## 15.	Fill missing values in department using the mode.

In [71]:
df

,employee_id,full_name,age,gender,email,phone,city,country,department,job_title,...,training_hours,remote_work,last_promotion_year,manager_id,team_size,monthly_leaves_taken,attrition_risk,salary_currency,linkedin_profile,contract_end_date
0,EMP3387,Neha Patel,37.0,Non-Binary,neha.patel@company.in,-7545786564,Mumbai,India,Marketing,SEO Specialist,...,129.42,TRUE,2024.0,EMP1010,14.0,1.2,High,AUD,linkedin.com/in/nehapatel373,08-10-2026
1,EMP2682,Ava Reddy,25.0,Prefer not to say,ava.reddy@yahoo.com,(957) 427-1356,Sydney,Australia,Product,Senior PM,...,62.98,FALSE,NaN,EMP2233,12.0,0.9,Medium,CAD,linkedin.com/in/avareddy878,NaN
2,EMP1964,Aarav Moore,51.0,Prefer not to say,aarav.moore@gmail.com,NaN,Kolkata,India,Product,Group PM,...,175.35,FALSE,2023.0,EMP1532,14.0,1.6,High,USD,linkedin.com/in/aaravmoore847,NaN
3,EMP1915,Amelia Bose,45.0,Prefer not to say,amelia.bose@hotmail.com,-7968601888,Bangalore,India,Engineering,Engineering Manager,...,166.99,TRUE,2022.0,EMP1772,1.0,1.7,High,CAD,linkedin.com/in/ameliabose880,27-03-2025
4,EMP1851,Divya Singh,22.0,M,divya.singh@hotmail.com,9.17522E+11,Delhi,India,Finance,Finance Manager,...,2.03,TRUE,2011.0,EMP1518,16.0,0.5,High,CAD,linkedin.com/in/divyasingh970,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,EMP2340,Rajesh Wilson,27.0,Male,rajesh.wilson@corp.com,-7562033622,Dubai,UAE,Sales,Account Executive,...,131.25,TRUE,2013.0,EMP2907,19.0,2.5,Medium,USD,NaN,NaN
2036,EMP1915,Charlotte Iyer,58.0,Female,charlotte.iyer@hotmail.com,-6956,San Francisco,USA,engeneering,HR Manager,...,177.32,TRUE,2019.0,EMP3897,9.0,4.8,Low,GBP,linkedin.com/in/charlotteiyer400,NaN
2037,EMP2809,Jackson Johnson,43.0,F,jackson.johnson@yahoo.com,-2228,New York,USA,Finance,Finance Manager,...,25.56,TRUE,NaN,EMP1705,13.0,0.4,Low,USD,linkedin.com/in/jacksonjohnson654,NaN
2038,EMP2323,Arjun Miller,33.0,Prefer not to say,arjun.miller@outlook.com,9421402810,Pune,India,Product,Product Manager,...,168.34,FALSE,2020.0,EMP3073,11.0,4.9,Low,INR,linkedin.com/in/arjunmiller688,NaN
2039,EMP2049,Charlotte Verma,31.0,Non-Binary,charlotte@verma,NaN,Dubai,UAE,Product,Product Analyst,...,189.13,FALSE,2013.0,EMP1479,5.0,3.9,Medium,CAD,linkedin.com/in/charlotteverma297,NaN

In [72]:
df['job_title'].isnull().sum()

np.int64(0)

In [73]:
df['department'].mode()

0    Operations
Name: department, dtype: object

In [75]:
df['department']=df.groupby('job_title')['department'].transform(lambda x: x.fillna(x.mode()[0] if not x.mode().empty else np.nan))

In [77]:
df['department'].isnull().sum()

np.int64(0)

## 16.	Fill missing values in job_title using the mode.

In [78]:
df['job_title'].isnull().sum()

np.int64(0)

## 17.	Fill missing values in education_level using the mode.

In [86]:
pd.set_option('display.max_columns',None)

In [88]:
df[['job_title','education_level']]

                job_title education_level
0          SEO Specialist        Master's
1               Senior PM     High School
2                Group PM       Associate
3     Engineering Manager             PhD
4         Finance Manager       Associate
...                   ...             ...
2035    Account Executive             MCA
2036           HR Manager        BE/BTech
2037      Finance Manager             MCA
2038      Product Manager      Bachelor's
2039      Product Analyst     High School

[2040 rows x 2 columns]

In [89]:
df['education_level'].mode()

0    MCA
Name: education_level, dtype: object

In [92]:
df['education_level']=df.groupby('job_title')['education_level'].transform(lambda x: x.fillna(x.mode()[0] if not x.mode().empty else np.nan))

In [94]:
df['education_level'].isnull().sum()

np.int64(0)

## 18.	Fill missing values in annual_salary using the department-wise median salary.

In [96]:
df[['department','annual_salary']]

       department annual_salary
0       Marketing       1295098
1         Product       1430387
2         Product       1889444
3     Engineering       1723986
4         Finance  â‚¹1,159,623
...           ...           ...
2035        Sales       1271741
2036  engeneering        681941
2037      Finance       1470895
2038      Product       1147268
2039      Product    â‚¹804,630

[2040 rows x 2 columns]

In [100]:
df['annual_salary']=pd.to_numeric(df['annual_salary'].astype(str).str.replace(',',''),errors='coerce')

In [102]:
df['annual_salary']=df.groupby('department')['annual_salary'].transform(lambda x: x.fillna(x.median()))

In [103]:
df['annual_salary'].isnull().sum()

np.int64(0)

## 19.	Fill missing values in bonus_percentage using the median.

In [104]:
df.columns

Index(['employee_id', 'full_name', 'age', 'gender', 'email', 'phone', 'city',
       'country', 'department', 'job_title', 'employment_type',
       'education_level', 'join_date', 'exit_date', 'years_of_experience',
       'annual_salary', 'bonus_percentage', 'performance_rating', 'nps_score',
       'projects_completed', 'training_hours', 'remote_work',
       'last_promotion_year', 'manager_id', 'team_size',
       'monthly_leaves_taken', 'attrition_risk', 'salary_currency',
       'linkedin_profile', 'contract_end_date'],
      dtype='object')

In [112]:
df['bonus_percentage']=df.groupby('department')['bonus_percentage'].transform(lambda x: x.fillna(x.median()))

In [113]:
df['bonus_percentage'].isnull().sum()

np.int64(0)

## 20.	Fill missing values in performance_rating using the mode.

In [114]:
df.columns

Index(['employee_id', 'full_name', 'age', 'gender', 'email', 'phone', 'city',
       'country', 'department', 'job_title', 'employment_type',
       'education_level', 'join_date', 'exit_date', 'years_of_experience',
       'annual_salary', 'bonus_percentage', 'performance_rating', 'nps_score',
       'projects_completed', 'training_hours', 'remote_work',
       'last_promotion_year', 'manager_id', 'team_size',
       'monthly_leaves_taken', 'attrition_risk', 'salary_currency',
       'linkedin_profile', 'contract_end_date'],
      dtype='object')

In [115]:
df['performance_rating'].mode()

0    Average
Name: performance_rating, dtype: object

In [117]:
df['performance_rating']=df.groupby(['job_title','department'])['performance_rating'].transform(lambda x: x.fillna(x.mode()[0] if not x.mode().empty else np.nan))

In [118]:
df['performance_rating'].isnull().sum()

np.int64(0)

## 21.	Fill missing values in training_hours using the median.

In [120]:
df['training_hours']=df.groupby('department')['training_hours'].transform(lambda x: x.fillna(x.median()))

In [121]:
df['training_hours'].isnull().sum()

np.int64(0)

## 22.	Fill missing values in team_size using the median.

In [223]:
df['team_size']=df.groupby('department')['team_size'].transform(lambda x: x.fillna(x.median))

In [224]:
df['team_size'].isnull().sum()

np.int64(0)

## 23.	Fill missing values in nps_score using the median.

In [125]:
df.columns

Index(['employee_id', 'full_name', 'age', 'gender', 'email', 'phone', 'city',
       'country', 'department', 'job_title', 'employment_type',
       'education_level', 'join_date', 'exit_date', 'years_of_experience',
       'annual_salary', 'bonus_percentage', 'performance_rating', 'nps_score',
       'projects_completed', 'training_hours', 'remote_work',
       'last_promotion_year', 'manager_id', 'team_size',
       'monthly_leaves_taken', 'attrition_risk', 'salary_currency',
       'linkedin_profile', 'contract_end_date'],
      dtype='object')

In [127]:
df['nps_score']=df.groupby('performance_rating')['nps_score'].transform(lambda x: x.fillna(x.median()))

In [128]:
df['nps_score'].isnull().sum()

np.int64(0)

## 24.	Fill missing values in manager_id with "No Manager".

In [131]:
df['manager_id'].isnull().sum()

np.int64(117)

In [133]:
df['manager_id']=df['manager_id'].fillna('No Manager')

In [134]:
df['manager_id'].isnull().sum()

np.int64(0)

## 25.	Handle missing values in contract_end_date appropriately.

In [135]:
df['employment_type'] = np.where(
    df['contract_end_date'].isna(),
    'Permanent',
    'Contract'
)

In [137]:
df['contract_end_date'].isnull().sum()

np.int64(1485)

In [138]:
df['contract_end_date']=df['contract_end_date'].fillna('Permenent')

In [139]:
df['contract_end_date'].isnull().sum()

np.int64(0)

In [140]:
df.isnull().sum()

employee_id                0
full_name                 52
age                        0
gender                     0
email                     41
phone                    355
city                       0
country                    0
department                 0
job_title                  0
employment_type            0
education_level            0
join_date                  0
exit_date               1621
years_of_experience        0
annual_salary              0
bonus_percentage           0
performance_rating         0
nps_score                  0
projects_completed         0
training_hours             0
remote_work               29
last_promotion_year      199
manager_id                 0
team_size                  0
monthly_leaves_taken     101
attrition_risk             0
salary_currency           98
linkedin_profile         296
contract_end_date          0
dtype: int64

In [141]:
df['full_name']=df['full_name'].fillna('Unknown_employee')

In [142]:
df['email']=df['email'].fillna('Not Available')

In [143]:
df['phone']=df['phone'].fillna('Not Available')

In [146]:
df['remote_work']=df.groupby('job_title')['remote_work'].transform(lambda x: x.fillna(x.mode()[0] if not x.mode().empty else np.nan))

In [149]:
df['join_date'].isnull().sum()

np.int64(0)

In [151]:
df['last_promotion_year']=df.groupby('department')['last_promotion_year'].transform(lambda x: x.fillna(x.median()))

In [152]:
df['last_promotion_year'].isnull().sum()

np.int64(0)

In [154]:
df['monthly_leaves_taken']=df.groupby('department')['monthly_leaves_taken'].transform(lambda x: x.fillna(x.median()))

In [156]:
df['salary_currency']=df.groupby('country')['salary_currency'].transform(lambda x: x.fillna(x.mode()[0] if not x.mode().empty else np.nan))

In [157]:
df['linkedin_profile']=df['linkedin_profile'].fillna('Not Available')

In [161]:
df.isnull().sum()

employee_id                0
full_name                  0
age                        0
gender                     0
email                      0
phone                      0
city                       0
country                    0
department                 0
job_title                  0
employment_type            0
education_level            0
join_date                  0
exit_date               1621
years_of_experience        0
annual_salary              0
bonus_percentage           0
performance_rating         0
nps_score                  0
projects_completed         0
training_hours             0
remote_work                0
last_promotion_year        0
manager_id                 0
team_size                  0
monthly_leaves_taken       0
attrition_risk             0
salary_currency            0
linkedin_profile           0
contract_end_date          0
dtype: int64

In [159]:
df.to_csv('Employee Cleaned Data.csv',index=False)

In [162]:
dfc=df.copy

# Phase 3: Text Standardization

## 26.	Standardize values in the gender column.

Example:
M, Male → Male
F, Female → Female
NB, Non-Binary → Non-Binary

In [164]:
df['gender'].unique()

array(['Non-Binary', 'Prefer not to say', 'M', 'Male', 'Female', 'F',
       'FEMALE', 'femal', 'male'], dtype=object)

In [167]:
df['gender']=df['gender'].str.capitalize()

In [168]:
df['gender'].unique()

array(['Non-binary', 'Prefer not to say', 'M', 'Male', 'Female', 'F',
       'Femal'], dtype=object)

In [169]:
a={'M':'Male',
  'F':'Female',
  'Femal':'Female'}

In [171]:
df['gender']=df['gender'].replace(a)

In [172]:
df['gender'].unique()

array(['Non-binary', 'Prefer not to say', 'Male', 'Female'], dtype=object)

## 27.	Standardize values in the remote_work column.

In [173]:
df['remote_work'].unique()

array(['TRUE', 'FALSE', 'yes', '0', 'Yes', '1', 'No', 'no'], dtype=object)

In [175]:
df['remote_work']=df['remote_work'].str.capitalize()

In [176]:
df['remote_work'].unique()

array(['True', 'False', 'Yes', '0', '1', 'No'], dtype=object)

In [177]:
# Yes=1,No=0

In [178]:
b={'True':'Yes',
  'False':'No',
  1:'Yes',
  0:'No'}

In [180]:
df['remote_work']=df['remote_work'].replace(b)

In [181]:
df['remote_work'].unique()

array(['Yes', 'No', '0', '1'], dtype=object)

## 28.	Standardize department names.

In [182]:
df['department'].unique()

array(['Marketing', 'Product', 'Engineering', 'Finance',
       'Customer Support', 'HR', 'Operations', 'Legal', 'Data Science',
       'Sales', 'Finace', 'HR ', 'engeneering', 'Data science', 'Slaes',
       'Engg'], dtype=object)

In [184]:
df['department']=df['department'].str.strip()

In [185]:
df['department'].unique()

array(['Marketing', 'Product', 'Engineering', 'Finance',
       'Customer Support', 'HR', 'Operations', 'Legal', 'Data Science',
       'Sales', 'Finace', 'engeneering', 'Data science', 'Slaes', 'Engg'],
      dtype=object)

In [188]:
df['department']=df['department'].str.capitalize()

In [189]:
df['department'].unique()

array(['Marketing', 'Product', 'Engineering', 'Finance',
       'Customer support', 'Hr', 'Operations', 'Legal', 'Data science',
       'Sales', 'Finace', 'Engeneering', 'Slaes', 'Engg'], dtype=object)

In [191]:
c={'Finace':'Finance',
  'Engeneering':'Engineering',
  'Slaes':'Sales',
  'Engg':'Engineering'}

In [192]:
df['department']=df['department'].replace(c)

In [193]:
df['department'].unique()

array(['Marketing', 'Product', 'Engineering', 'Finance',
       'Customer support', 'Hr', 'Operations', 'Legal', 'Data science',
       'Sales'], dtype=object)

## 29.	Standardize city names.

In [195]:
df['city'].unique()

array(['Mumbai', 'Sydney', 'Kolkata', 'Bangalore', 'Delhi', 'Singapore',
       'Pune', 'Hyderabad', 'San Francisco', 'Toronto', 'Ahmedabad',
       'London', 'Dubai', 'Chennai', 'New York'], dtype=object)

## 30.	Standardize country names.

In [197]:
df['country'].unique()

array(['India', 'Australia', 'Singapore', 'USA', 'Canada', 'UK', 'UAE'],
      dtype=object)

## 31.	Convert email addresses to lowercase.

In [198]:
df['email'].unique()

array(['neha.patel@company.in', 'ava.reddy@yahoo.com',
       'aarav.moore@gmail.com', ..., 'rajesh.wilson@corp.com',
       'jackson.johnson@yahoo.com', 'arjun.miller@outlook.com'],
      shape=(1764,), dtype=object)

In [200]:
df['email']=df['email'].str.lower()

In [202]:
df['email'].unique()

array(['neha.patel@company.in', 'ava.reddy@yahoo.com',
       'aarav.moore@gmail.com', ..., 'rajesh.wilson@corp.com',
       'jackson.johnson@yahoo.com', 'arjun.miller@outlook.com'],
      shape=(1764,), dtype=object)

## 32.	Remove leading and trailing spaces from all text columns.

In [209]:
df[df.select_dtypes(include='object').columns]=df.select_dtypes(include='object').apply(lambda x: x.str.strip())

## 33.	Standardize job titles.

In [212]:
df.columns

Index(['employee_id', 'full_name', 'age', 'gender', 'email', 'phone', 'city',
       'country', 'department', 'job_title', 'employment_type',
       'education_level', 'join_date', 'exit_date', 'years_of_experience',
       'annual_salary', 'bonus_percentage', 'performance_rating', 'nps_score',
       'projects_completed', 'training_hours', 'remote_work',
       'last_promotion_year', 'manager_id', 'team_size',
       'monthly_leaves_taken', 'attrition_risk', 'salary_currency',
       'linkedin_profile', 'contract_end_date'],
      dtype='object')

In [214]:
df['job_title'].unique()

array(['SEO Specialist', 'Senior PM', 'Group PM', 'Engineering Manager',
       'Finance Manager', 'Senior Analyst', 'Team Lead', 'HR Executive',
       'Marketing Manager', 'Product Manager', 'Supply Chain Analyst',
       'Senior Counsel', 'ML Engineer', 'Senior Sales Rep',
       'Senior Data Scientist', 'Financial Analyst', 'Senior Agent',
       'VP Support', 'DevOps Engineer', 'COO', 'HR Business Partner',
       'Head of Data', 'Data Analyst', 'Recruiter', 'CHRO', 'HR Manager',
       'Support Agent', 'Software Engineer', 'Marketing Analyst', 'CMO',
       'Product Analyst', 'Content Strategist', 'Controller',
       'Legal Manager', 'Ops Manager', 'Logistics Coordinator',
       'VP Sales', 'Associate', 'Data Scientist', 'CLO', 'Sales Rep',
       'Account Executive', 'CPO', 'Senior SWE', 'Support Manager',
       'Legal Counsel', 'CFO', 'Lead Engineer', 'Operations Analyst',
       'Sales Manager'], dtype=object)

In [ ]:
# COO,CHRO,CMO,CLO,CPO,CFO

In [216]:
df['job_title']=df['job_title'].replace({'COO':'Chief Operating Officer',
                        'CHRO':'Chief Human Resources Officer',
                        'CMO':'Chief Marketing Officer',
                        'CLO':'Chief Legal Officer',
                        'CPO':'Chief Product Officer',
                        'CFO':'Chief Financial Officer'})

In [217]:
df['job_title'].unique()

array(['SEO Specialist', 'Senior PM', 'Group PM', 'Engineering Manager',
       'Finance Manager', 'Senior Analyst', 'Team Lead', 'HR Executive',
       'Marketing Manager', 'Product Manager', 'Supply Chain Analyst',
       'Senior Counsel', 'ML Engineer', 'Senior Sales Rep',
       'Senior Data Scientist', 'Financial Analyst', 'Senior Agent',
       'VP Support', 'DevOps Engineer', 'Chief Operating Officer',
       'HR Business Partner', 'Head of Data', 'Data Analyst', 'Recruiter',
       'Chief Human Resources Officer', 'HR Manager', 'Support Agent',
       'Software Engineer', 'Marketing Analyst',
       'Chief Marketing Officer', 'Product Analyst', 'Content Strategist',
       'Controller', 'Legal Manager', 'Ops Manager',
       'Logistics Coordinator', 'VP Sales', 'Associate', 'Data Scientist',
       'Chief Legal Officer', 'Sales Rep', 'Account Executive',
       'Chief Product Officer', 'Senior SWE', 'Support Manager',
       'Legal Counsel', 'Chief Financial Officer', 'Lead Engineer',
       'Operations Analyst', 'Sales Manager'], dtype=object)

## 34.	Clean LinkedIn profile URLs if available.

In [220]:
df['linkedin_profile'].unique()

array(['linkedin.com/in/nehapatel373', 'linkedin.com/in/avareddy878',
       'linkedin.com/in/aaravmoore847', ...,
       'linkedin.com/in/jacksonjohnson654',
       'linkedin.com/in/arjunmiller688',
       'linkedin.com/in/charlotteverma297'], shape=(1706,), dtype=object)

In [225]:
df.isnull().sum()

employee_id                0
full_name                  0
age                        0
gender                     0
email                      0
phone                      0
city                       0
country                    0
department                 0
job_title                  0
employment_type            0
education_level            0
join_date                  0
exit_date               1621
years_of_experience        0
annual_salary              0
bonus_percentage           0
performance_rating         0
nps_score                  0
projects_completed         0
training_hours             0
remote_work                0
last_promotion_year        0
manager_id                 0
team_size                  0
monthly_leaves_taken       0
attrition_risk             0
salary_currency            0
linkedin_profile           0
contract_end_date          0
dtype: int64

In [227]:
df.drop('exit_date',axis=1,inplace=True)

In [228]:
df.isnull().sum()

employee_id             0
full_name               0
age                     0
gender                  0
email                   0
phone                   0
city                    0
country                 0
department              0
job_title               0
employment_type         0
education_level         0
join_date               0
years_of_experience     0
annual_salary           0
bonus_percentage        0
performance_rating      0
nps_score               0
projects_completed      0
training_hours          0
remote_work             0
last_promotion_year     0
manager_id              0
team_size               0
monthly_leaves_taken    0
attrition_risk          0
salary_currency         0
linkedin_profile        0
contract_end_date       0
dtype: int64

In [229]:
df.to_csv('Employee Data Cleaned.csv',index=False)